@startuml
title Database Classes

package Zend\Db\TableGateway {
	class TableGateway
}

package SAccounts\Storage\Account {

	class ZendDb

	package ZendDB {

		enum RecordStatus {
			ACTIVE
			SUSPENDED
			DEFUNCT
		}

		class OrgTableGateway<sa_org>
		class ChartTableGateway<sa_coa>
		class ChartLedgerTableGateway<sa_coa_ledger>
		class ChartLedgerLinkTableGateway<sa_coa_link>
	}
}

TableGateway <|-- OrgTableGateway
TableGateway <|-- ChartTableGateway
TableGateway <|-- ChartLedgerTableGateway
TableGateway <|-- ChartLedgerLinkTableGateway
ChartLedgerLinkTableGateway *-- ChartLedgerTableGateway
RecordStatus <.. OrgTableGateway
RecordStatus <.. ChartTableGateway
RecordStatus <. ChartLedgerTableGateway
RecordStatus <.. ChartLedgerLinkTableGateway


@enduml